version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234567890
    ports:
      - "3306:3306"

  app:
    depends_on:
      - mysqldb
    build: ./docker-proj
    ports:
      - "3000:3000"
    entrypoint: [ sleep, "3000" ]
